### PR TITLE
Add a timeout to meetings

### LINKED ISSUE #2: add a timeout
our meeting hasn't closed in two weeks cos the chair is away.  add a timeout

### PR DESCRIPTION
**Pull request by adriaandegroot**
If there is silence for 30 minutes, end the meeting if it is in-progress.

Fixes #2

### CODE REVIEW

**Comment by adriaandegroot** [comment]
@a-andreyev  @jriddell  please take a look if this closes the meeting automatically for you (after 30 minutes -- you might want to dial that back down by editing the source code during testing).

**Comment by a-andreyev** [comment]
Cool, thank you! cc: @Justinzobel

**Comment by Justinzobel** [comment]
This should now be running on our instance.

**Comment by Justinzobel** [comment]
I haven't heard any feedback from the team and this has been running in the system since my comment above. I think this can be merged.

**Pull request merged**
